### ISSUE TITLE
Solver Exception Error

### ISSUE THREAD

**Issue by Raghavdata** [alexloboda/gmwcs-solver#1]
Hi Alex,
I was trying to get your solver to work for an application called ShinyGam, you could read about the application on the following link :

https://artyomovlab.wustl.edu/shiny/gam/ .

The application basically calls your solver and gives the nodes and edges file generated in the application to GMWCS solver. But, before sending the nodes files and edge files it transforms the metabolomic and genomic data into the node and edge files. The sample data for this can be found on the following link:

http://artyomovlab.wustl.edu/publications/supp_materials/GAM_2015/Ctrl.vs.MandLPSandIFNg.gene.de.tsv

and

http://artyomovlab.wustl.edu/publications/supp_materials/GAM_2015/Ctrl.vs.MandLPSandIFNg.met.de.tsv

After installing the GMWCS solver the error we got was as follows: 

Error occured while solving:null

We first checked whether the files that were being input were correct or not and found them to be in the format as required by GMWCS. Further, no Parse Exception confirmed that we were inputing the right files. 
Then, we checked whether the CPLEX files required were in the correct directory and that too was correct.
We then tried to track the error and came to the conclusion that the error was happening because of the Solver Exception being called in Main.java which in turn is being called by the Undirected Graph in Solver.java .
We were unable to track the root of the error beyond this.
We would be grateful if you could guide us as to what the error might be and how we could solve it.

**Comment by assaron** [comment]
Hi Raghavdata,

I believe we didn't mention anywhere, Shiny GAM uses nosignal branch (https://github.com/alexloboda/gmwcs-solver/tree/nosignal). Can you try to use it? I hope it will solve the problem. If not, please, attach files that Shiny GAM generates (nodes.txt and edges.txt).

Alexey

**Comment by Raghavdata** [comment]
Hey,
So the error persists even after using the nosignal tree. The output was as follows:

Graph decomposing takes 0.422 seconds.
Error occur while solving:null

Awaiting your reply

Raghav Sehgal

**Comment by assaron** [comment]
Can you upload nodes.txt and edges.txt files here:
https://www.dropbox.com/request/vdTq5tpnvMRs2xjOWH51 ?

---
a

**Comment by alexloboda** [comment]
Hi Raghavdata,

Try to pull changes from `nosignal` brunch and run it again, I hope you'll get more informative message than before.
